In [2]:
import pandas as pd
import numpy as np

# Set a random seed for reproducibility
np.random.seed(42)

# Create a date range
date_range = pd.date_range(start='2023-01-01', end='2023-01-21', freq='D')

# Generate random returns for three assets 'A', 'B', and 'C'
returns_data = {
    'A': np.random.normal(0.001, 0.01, len(date_range)),
    'B': np.random.normal(0.0005, 0.015, len(date_range)),
    'C': np.random.normal(0.0015, 0.012, len(date_range))
}

# Create the returns DataFrame
returns_df = pd.DataFrame(returns_data, index=date_range)

# Compute the covariance matrix
cov_matrix = returns_df.cov()

# Print the covariance DataFrame
print("Covariance DataFrame:")
print(cov_matrix)

# Print the covariance matrix values as a numpy array
print("\nCovariance Matrix Values:")
print(cov_matrix.values)

Covariance DataFrame:
          A         B         C
A  0.000100 -0.000017 -0.000027
B -0.000017  0.000180 -0.000012
C -0.000027 -0.000012  0.000095

Covariance Matrix Values:
[[ 1.00317168e-04 -1.74895666e-05 -2.70971276e-05]
 [-1.74895666e-05  1.80028470e-04 -1.19734770e-05]
 [-2.70971276e-05 -1.19734770e-05  9.53099026e-05]]


In [4]:
returns_df.to_csv('/workspaces/backtesting/investment-portfolio-project/data/synthetic_portfolio.csv')
